[project]
name = "yt-video-downloader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pytubefix>=10.3.6",
    "streamlit>=1.54.0",
]
